---
- name: Create New Folder
  hosts: "{{ ComputerName }}"
  gather_facts: yes
  tasks:
    - name: Run PowerShell script
      ansible.windows.win_powershell:
        script: |
          $ActionTask = 'new folder'
          $ComputerName = {{ COMPUTER_NAME }}
          $FolderPath = {{ FOLDER_PATH }}

          # Execute Powershell Script in Windows Host
          Try {
              $ErrorActionPreference = 'Stop'
              
              If (!(Test-Path $FolderPath)) {
                New-Item -Path $FolderPath -ItemType directory
                Write-Output "INFO: [$ActionTask]: Folder [$FolderPath] created successfully"
              }
              else {
                Write-Output "INFO: [$ActionTask]: Folder [$FolderPath] already exists - no action taken."
              }
            }
              Catch {
              #$_
                  Write-Output "ERROR: [$ActionTask]: An  error has occured creating folder [$FolderPath]. Error details: $($_.Exception.Message)"
              }
         
      register: ps_output
    - name: Display Powershell Output
      ansible.builtin.debug:
         var: ps_output
