---
- name: Execute PowerShell script from GitHub
  hosts: "{{ Hostname }}"
  gather_facts: false
  tasks:
    - name: Run PowerShell script
      ansible.windows.win_powershell:
        script: |
           # Read the PowerShell script content from the GitHub repository
           # (e.g., using Get-Content or by directly including the script here)
           # Example: If your script is named 'myscript.ps1' in the repo root
           #$scriptContent = Get-Content ".scripts\powershell\test.ps1"
           #Invoke-Expression $scriptContent

           # Alternatively, if the script is simple, you can directly embed it
           Write-Host "Executing PowerShell script to {{ Hostname }}!"
           Systemctl show ssh.service
      register: ps_output
    - name: Display Powershell Output
      ansible.builtin.debug:
         var: ps_output
